plugins {
    alias(libs.plugins.android.application)
    alias(libs.plugins.kotlin.android)
    id("com.universalglasses.rayneo.app")
}

import java.util.Properties

// Device-specific local config (do NOT commit secrets).
// Recommended: set these in local.properties (generated by xg-glass init), e.g.:
//   rokid.clientSecret=...
//   rokid.snRawName=sn_your_file_name_without_extension
val _localProps = Properties()
val _localPropsFile = rootProject.file("local.properties")
if (_localPropsFile.exists()) {
    _localPropsFile.inputStream().use { _localProps.load(it) }
}
fun _propOrEnv(key: String, envKey: String): String =
    (_localProps.getProperty(key) ?: System.getenv(envKey) ?: "").trim()
fun _escapeForBuildConfig(s: String): String =
    s.replace("\\", "\\\\").replace("\"", "\\\"")

val rokidClientSecret = _propOrEnv("rokid.clientSecret", "ROKID_CLIENT_SECRET")
val rokidSnRawName = _propOrEnv("rokid.snRawName", "ROKID_SN_RAW_NAME")
val metaAppId = _propOrEnv("meta.applicationId", "META_APPLICATION_ID")

android {
    namespace = "com.example.xgglassapp"
    compileSdk = 34

    defaultConfig {
        // Meta Wearables Application ID placeholder
        // Defaults to "0" (Developer Mode) if not set.
        val resolvedMetaAppId = if (metaAppId.isNotEmpty()) metaAppId else "0"
        manifestPlaceholders["META_APPLICATION_ID"] = resolvedMetaAppId
        applicationId = "com.example.xgglassapp"
        minSdk = 29
        targetSdk = 34
        versionCode = 1
        versionName = "0.0.1"

        buildConfigField("boolean", "XG_SIMULATOR", "false")
        buildConfigField("String", "ROKID_CLIENT_SECRET", "\"${_escapeForBuildConfig(rokidClientSecret)}\"")
        buildConfigField("String", "ROKID_SN_RAW_NAME", "\"${_escapeForBuildConfig(rokidSnRawName)}\"")
    }

    buildFeatures {
        buildConfig = true
    }

    // Keep APK size reasonable when Flutter is present (Frame integration).
    // Generate per‑ABI APKs instead of one universal APK.
    splits {
        abi {
            isEnable = true
            reset()
            // Most real devices are arm64; keep armeabi-v7a for older 32-bit phones.
            // If you need to run on the Android emulator, add "x86_64" here.
            include("arm64-v8a", "armeabi-v7a")
            isUniversalApk = false
        }
    }

    buildTypes {
        debug { }
        release {
            isMinifyEnabled = false
        }
    }

    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_1_8
        targetCompatibility = JavaVersion.VERSION_1_8
    }
    kotlinOptions {
        jvmTarget = "1.8"
    }
}

ugRayneo {
    // The generated RayNeo glass-host APK will load this class by reflection.
    appEntryClass.set("__XG_ENTRY_CLASS__")
    logicProjectPath.set(":ug_app_logic")
    // RayNeo/Mercury vendor AARs (used for temple gestures / navigation on glasses)
    // Replaced by xg-glass init: __XG_SDK_PATH__/third_party/rayneo/aar
    mercuryAarDir.set(File(rootDir, "__XG_SDK_PATH__/third_party/rayneo/aar").absolutePath)
    // hostProjectPath defaults to :ug_rayneo_glass_host
    // assetApkName defaults to rayneo_glass_app.apk
    // variant defaults to debug
}

dependencies {
    implementation(libs.kotlinx.coroutines.android)

    // universal_glasses (single entry-point dependency)
    implementation("com.universalglasses:universal:0.0.1")

    // Shared developer logic module (implements UniversalAppEntry)
    implementation(project(":ug_app_logic"))

    implementation("androidx.appcompat:appcompat:1.7.0")
    implementation("androidx.core:core-ktx:1.13.1")
    implementation("com.google.android.material:material:1.12.0")
}


