platform :ios, '16.0'

flutter_application_path = '../../../third_party/frame/frame_module'
load File.join(flutter_application_path, '.ios', 'Flutter', 'podhelper.rb')

target 'XgGlassSample' do
  install_all_flutter_pods(flutter_application_path)
end

target 'XgGlassSampleTests' do
  inherit! :search_paths
end

post_install do |installer|
  flutter_post_install(installer) if defined?(flutter_post_install)
end
