#!/usr/bin/env python3
"""Generate llms-full.txt from the curated llms.txt index."""

from __future__ import annotations

import re
import sys
from pathlib import Path


LINK_RE = re.compile(r"\[[^\]]+\]\(([^)]+\.md)\)")
SEPARATOR = "=" * 80


def _repo_root() -> Path:
    return Path(__file__).resolve().parents[1]


def _linked_markdown_files(llms_text: str) -> list[str]:
    seen: set[str] = set()
    ordered: list[str] = []
    for match in LINK_RE.finditer(llms_text):
        target = match.group(1)
        if target in seen:
            continue
        seen.add(target)
        ordered.append(target)
    return ordered


def _read_required(root: Path, target: str) -> str:
    path = root / target
    if not path.is_file():
        print(f"Missing llms.txt target: {target}", file=sys.stderr)
        raise SystemExit(1)
    return path.read_text(encoding="utf-8")


def generate() -> tuple[int, int]:
    root = _repo_root()
    llms_path = root / "llms.txt"
    llms_text = llms_path.read_text(encoding="utf-8")
    targets = _linked_markdown_files(llms_text)

    parts = [
        "# llms-full.txt\n",
        "\n",
        "Generated by scripts/gen_llms_full.py from llms.txt. DO NOT EDIT.\n",
        "\n",
        llms_text,
    ]
    if not llms_text.endswith("\n"):
        parts.append("\n")

    for target in targets:
        content = _read_required(root, target)
        parts.extend(
            [
                "\n",
                f"{SEPARATOR}\n",
                f"Source: {target}\n",
                f"{SEPARATOR}\n",
                content,
            ]
        )
        if not content.endswith("\n"):
            parts.append("\n")

    output = "".join(parts).rstrip("\n") + "\n"
    output_path = root / "llms-full.txt"
    output_path.write_text(output, encoding="utf-8")
    return len(targets), len(output.encode("utf-8"))


def main() -> int:
    count, byte_count = generate()
    print(f"Wrote llms-full.txt: {count} files, {byte_count} bytes")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
