from __future__ import annotations

import argparse
import os
import platform
import shutil
import tempfile
from pathlib import Path

from .adb import _find_adb_cmd, _pick_apk, _push_video_to_device, _read_application_id
from .config import _apply_overrides, _load_config, _validate_entry_class
from .constants import (
    DEFAULT_CONFIG_FILE,
    DEFAULT_SDK,
    DEFAULT_TEMPLATE,
    CliUsageError,
    _DEVICE_VIDEO_PATH,
    missing_sdk_checkout_message,
)
from .emulator import _ensure_emulator_running
from .gradle import _cap, _gradlew_path, _run
from .paths import _ensure_executable
from .prereqs import (
    _ensure_flutter_executables,
    _ensure_flutter_module_ready,
    _ensure_java_runtime,
    _ensure_project_sdk_dir,
    _find_flutter_cmd,
    _persist_env,
    _print_manual_shell_setup,
    _resolve_android_sdk,
    _write_local_properties,
)
from .scaffold import (
    _apply_cfg_to_project,
    _apply_sim_video_build_setting,
    _apply_simulator_build_settings,
    _copy_kt_into_project,
    _copy_tree,
    _infer_entry_class_from_kt,
)
from .video import _resolve_sim_video


def _arg_uses_default(value: str | None, default: Path) -> bool:
    return value is None or str(value) == str(default)


def _resolve_required_dir(
    raw_path: str | Path,
    *,
    label: str,
    subcommand: str,
    default_path: Path | None = None,
) -> Path:
    path = Path(raw_path).expanduser().resolve()
    if path.is_dir():
        return path
    if default_path is not None and _arg_uses_default(str(raw_path), default_path):
        raise CliUsageError(missing_sdk_checkout_message(subcommand))
    raise CliUsageError(f"{label} not found: {path}")


def _resolve_quick_run_template(sdk: Path, *, sdk_from_default: bool) -> Path:
    if DEFAULT_TEMPLATE.is_dir():
        return DEFAULT_TEMPLATE
    sdk_template = sdk / "templates" / "kotlin-app"
    if sdk_template.is_dir():
        return sdk_template
    if sdk_from_default:
        raise CliUsageError(missing_sdk_checkout_message("run"))
    raise CliUsageError(f"Template not found: {sdk_template}")


def cmd_init(args: argparse.Namespace) -> int:
    dst = Path(args.dir).expanduser().resolve()
    template = _resolve_required_dir(
        args.template,
        label="Template",
        subcommand="init",
        default_path=DEFAULT_TEMPLATE,
    )
    sdk = _resolve_required_dir(
        args.sdk,
        label="SDK",
        subcommand="init",
        default_path=DEFAULT_SDK,
    )
    entry_class = _validate_entry_class(args.entry_class, "--entry-class")

    if dst.exists() and any(dst.iterdir()):
        raise RuntimeError(f"Target dir must be empty: {dst}")
    dst.mkdir(parents=True, exist_ok=True)

    # Copy a curated subset of the template (avoid build/ caches).
    _copy_tree(template / "app", dst / "app")
    _copy_tree(template / "xgglass_app_logic", dst / "xgglass_app_logic")
    _copy_tree(template / "gradle", dst / "gradle")

    for f in [
        ".gitignore",
        "build.gradle.kts",
        "settings.gradle.kts",
        "gradle.properties",
        "gradlew",
        "gradlew.bat",
        "README.md",
        DEFAULT_CONFIG_FILE,
    ]:
        src = template / f
        if src.exists():
            shutil.copy2(src, dst / f)

    _ensure_executable(dst / "gradlew")

    # Patch includeBuild paths in settings.gradle.kts
    rel_sdk = Path(os.path.relpath(sdk, dst)).as_posix()
    settings_file = dst / "settings.gradle.kts"
    if settings_file.exists():
        s = settings_file.read_text(encoding="utf-8")
        # Stage2 template uses placeholders.
        s = s.replace("__XG_SDK_PATH__", rel_sdk)
        settings_file.write_text(s, encoding="utf-8")

    # Patch xgRayneo config in app/build.gradle.kts (entry class + mercury dir)
    app_gradle = dst / "app" / "build.gradle.kts"
    if app_gradle.exists():
        g = app_gradle.read_text(encoding="utf-8")
        g = g.replace("__XG_ENTRY_CLASS__", entry_class)
        g = g.replace("__XG_SDK_PATH__", rel_sdk)
        app_gradle.write_text(g, encoding="utf-8")

    manifest = dst / "app" / "src" / "main" / "AndroidManifest.xml"
    if manifest.exists():
        m = manifest.read_text(encoding="utf-8")
        m = m.replace("__XG_ENTRY_CLASS__", entry_class)
        manifest.write_text(m, encoding="utf-8")

    # Patch xg-glass.yaml (if template provides it).
    cfg_file = dst / DEFAULT_CONFIG_FILE
    if cfg_file.exists():
        c = cfg_file.read_text(encoding="utf-8")
        c = c.replace("__XG_SDK_PATH__", rel_sdk)
        c = c.replace("__XG_ENTRY_CLASS__", entry_class)
        cfg_file.write_text(c, encoding="utf-8")
    else:
        cfg_file.write_text(
            "\n".join(
                [
                    "# xg-glass config (generated by xg-glass init)",
                    f'sdkPath: "{rel_sdk}"',
                    f'entryClass: "{entry_class}"',
                    f'rayneoMercuryAarDir: "{rel_sdk}/third_party/rayneo/aar"',
                    'variant: "debug"',
                    'module: "app"',
                    'applicationId: "com.example.xgglassapp"',
                    "",
                ]
            ),
            encoding="utf-8",
        )

    # One-click bootstrap: ensure Java/Android SDK/Flutter are usable on a fresh machine,
    # then persist env vars for future shells (macOS: ~/.zshrc).
    env = {**os.environ}
    _ensure_java_runtime(env)
    android_sdk = _resolve_android_sdk()
    if android_sdk:
        env.setdefault("ANDROID_HOME", android_sdk)
        env.setdefault("ANDROID_SDK_ROOT", android_sdk)
    # Generate local.properties with sdk.dir + Rokid config.
    _write_local_properties(dst, android_sdk)
    # Ensure Flutter (downloads managed Flutter + runs pub get if needed).
    cfg = _load_config(dst, DEFAULT_CONFIG_FILE)
    _ensure_flutter_module_ready(dst, cfg)
    # Persist for future shells
    flutter = _find_flutter_cmd()
    if bool(getattr(args, "no_shell_setup", False)):
        _print_manual_shell_setup(java_home=env.get("JAVA_HOME"), android_sdk=android_sdk, flutter_bin=flutter)
    else:
        _persist_env(java_home=env.get("JAVA_HOME"), android_sdk=android_sdk, flutter_bin=flutter)

    if bool(getattr(args, "sim", False)):
        _apply_simulator_build_settings(dst, enabled=True)

    print(f"Created project: {dst}")
    print("Next:")
    print(f"  cd {dst}")
    print("  xg-glass build")
    print("  # If you prefer Gradle directly in a new terminal:")
    if platform.system() == "Darwin":
        print("  #   source ~/.zshrc")
    else:
        print("  #   restart your terminal")
    print("  #   ./gradlew :app:assembleDebug")
    print("  xg-glass install")
    print("  xg-glass run")
    return 0


def cmd_build(args: argparse.Namespace) -> int:
    project = Path(args.project).expanduser().resolve()
    sdk_override = None
    if args.sdk:
        sdk_override = str(_resolve_required_dir(args.sdk, label="SDK", subcommand="build"))
    cfg = _load_config(project, args.config)
    cfg = _apply_overrides(
        cfg,
        sdk=sdk_override,
        entry_class=args.entry_class,
        rayneo_aar_dir=args.rayneo_aar_dir,
        variant=args.variant,
        module=args.module,
    )
    _apply_cfg_to_project(project, cfg)

    # Ensure all development dependencies are available.
    # This allows standalone `xg-glass build` (without prior `init`) on a fresh machine.
    env = {**os.environ}
    _ensure_java_runtime(env)
    android_sdk = _resolve_android_sdk()
    if android_sdk:
        env.setdefault("ANDROID_HOME", android_sdk)
        env.setdefault("ANDROID_SDK_ROOT", android_sdk)
        # Ensure project local.properties has sdk.dir (may be missing if user
        # cloned the project instead of using `xg-glass init`).
        _ensure_project_sdk_dir(project, android_sdk)
    _ensure_flutter_module_ready(project, cfg)

    # Persist env vars so future shells (e.g. manual ./gradlew) also work.
    # Idempotent – no-op if already written.
    flutter = _find_flutter_cmd()
    _persist_env(java_home=env.get("JAVA_HOME"), android_sdk=android_sdk, flutter_bin=flutter)

    # Gradle's Flutter plugin invokes engine binaries (impellerc, gen_snapshot).
    # On macOS these may carry quarantine; strip before Gradle runs.
    _ensure_flutter_executables()

    variant = cfg.variant
    module = cfg.module
    gradlew = _gradlew_path(project)
    task = f":{module}:assemble{_cap(variant)}"
    _run([str(gradlew), task], cwd=project, env=env)
    apk_dir = project / module / "build" / "outputs" / "apk" / variant
    print(f"Build OK. APK outputs under: {apk_dir}")
    return 0


def cmd_install(args: argparse.Namespace) -> int:
    project = Path(args.project).expanduser().resolve()
    cfg = _load_config(project, args.config)
    cfg = _apply_overrides(cfg, variant=args.variant, module=args.module)
    module = cfg.module
    variant = cfg.variant

    apk = Path(args.apk).expanduser().resolve() if args.apk else _pick_apk(project, module, variant, args.serial)
    if not apk.exists():
        raise FileNotFoundError(f"APK not found: {apk}")

    cmd = [_find_adb_cmd()]
    if args.serial:
        cmd += ["-s", args.serial]
    cmd += ["install", "-r", str(apk)]
    _run(cmd, cwd=project)
    print(f"Installed: {apk.name}")
    return 0


def cmd_run(args: argparse.Namespace) -> int:
    # Stage 3: quick mode - run a single .kt file by generating a project.
    if getattr(args, "kt_file", None) and str(args.kt_file).lower().endswith(".kt"):
        kt = Path(args.kt_file).expanduser().resolve()
        if not kt.exists():
            raise FileNotFoundError(f"Kotlin file not found: {kt}")

        sdk_from_default = not getattr(args, "sdk", None)
        if not sdk_from_default:
            sdk = _resolve_required_dir(args.sdk, label="SDK", subcommand="run")
        else:
            sdk = _resolve_required_dir(
                DEFAULT_SDK,
                label="SDK",
                subcommand="run",
                default_path=DEFAULT_SDK,
            )
        template = _resolve_quick_run_template(sdk, sdk_from_default=sdk_from_default)

        raw_entry_class = getattr(args, "entry_class", None)
        entry_class = raw_entry_class or _infer_entry_class_from_kt(kt)
        if not entry_class:
            raise RuntimeError(
                "Failed to infer entry class from .kt file. Please ensure the file has a `package ...` line and a top-level `class`, "
                "or pass --entry-class explicitly."
            )
        entry_class = _validate_entry_class(
            entry_class,
            "--entry-class" if raw_entry_class else "inferred entry class",
        )

        if getattr(args, "save", None):
            project_dir = Path(args.save).expanduser().resolve()
            if project_dir.exists() and any(project_dir.iterdir()):
                raise RuntimeError(f"--save directory must be empty: {project_dir}")
            project_dir.parent.mkdir(parents=True, exist_ok=True)
            project_dir.mkdir(parents=True, exist_ok=True)
            keep = True
        else:
            base = Path.cwd() / ".xg_glass_tmp"
            base.mkdir(parents=True, exist_ok=True)
            project_dir = Path(tempfile.mkdtemp(prefix="run-", dir=str(base)))
            keep = bool(getattr(args, "keep_tmp", False))

        _init_project(dst=project_dir, template=template, sdk=sdk, entry_class=entry_class)
        _copy_kt_into_project(project_dir, kt)

        if bool(getattr(args, "sim", False)):
            _apply_simulator_build_settings(project_dir, enabled=True)

        # Resolve video source for sim mode (--local_video or --video_url).
        sim_video: Path | None = None
        if bool(getattr(args, "sim", False)):
            sim_video = _resolve_sim_video(args)
            if sim_video is not None:
                _apply_sim_video_build_setting(project_dir, _DEVICE_VIDEO_PATH)

        # One-shot: build + install + run.
        cmd_build(
            argparse.Namespace(
                project=str(project_dir),
                variant=args.variant,
                module=args.module,
                config=DEFAULT_CONFIG_FILE,
                entry_class=None,
                sdk=None,
                rayneo_aar_dir=None,
            )
        )
        # When --sim, ensure an Android Emulator is running before installing.
        if bool(getattr(args, "sim", False)):
            _ensure_emulator_running(serial=args.serial)

        # Push video to device before installing the app (so the app can find it on launch).
        if sim_video is not None:
            _push_video_to_device(sim_video, serial=args.serial)

        cmd_install(
            argparse.Namespace(
                project=str(project_dir),
                variant=args.variant,
                module=args.module,
                config=DEFAULT_CONFIG_FILE,
                serial=args.serial,
                apk=None,
            )
        )
        _run_project(
            argparse.Namespace(
                project=str(project_dir),
                variant=args.variant,
                module=args.module,
                config=DEFAULT_CONFIG_FILE,
                serial=args.serial,
                package=args.package,
                kt_file=None,
                save=None,
                keep_tmp=False,
                entry_class=None,
                sdk=None,
            )
        )

        if not keep:
            shutil.rmtree(project_dir, ignore_errors=True)
        else:
            print(f"Quick project kept at: {project_dir}")
        return 0

    return _run_project(args)


def _run_project(args: argparse.Namespace) -> int:
    project = Path(args.project).expanduser().resolve()
    cfg = _load_config(project, args.config)
    cfg = _apply_overrides(cfg, module=args.module, variant=args.variant)
    module = cfg.module
    package_name = args.package or cfg.application_id or _read_application_id(project, module) or "com.example.xgglassapp"

    cmd = [_find_adb_cmd()]
    if getattr(args, "serial", None):
        cmd += ["-s", args.serial]
    # Use monkey to avoid hardcoding activity component.
    cmd += ["shell", "monkey", "-p", package_name, "-c", "android.intent.category.LAUNCHER", "1"]
    _run(cmd, cwd=project)
    print(f"Launched: {package_name}")
    return 0


def _init_project(*, dst: Path, template: Path, sdk: Path, entry_class: str) -> None:
    """
    Internal helper: same behavior as `xg-glass init`, but callable from quick mode.
    """
    cmd_init(
        argparse.Namespace(
            dir=str(dst),
            template=str(template),
            sdk=str(sdk),
            entry_class=str(entry_class),
        )
    )
