from __future__ import annotations

import argparse
import os
import platform
import shutil
import subprocess
import tempfile
from pathlib import Path

from .adb import _find_adb_cmd, _pick_apk, _push_video_to_device, _read_application_id
from .config import _apply_overrides, _load_config, _validate_entry_class
from .constants import (
    DEFAULT_CONFIG_FILE,
    CliUsageError,
    _DEVICE_VIDEO_PATH,
)
from .devices import DeviceSelection, format_devices_yaml_value, parse_device_selection
from .emulator import _ensure_emulator_running
from .gradle import _cap, _gradlew_path, _run
from .paths import _ensure_executable
from .prereqs import (
    _ensure_flutter_executables,
    _ensure_flutter_module_ready,
    _ensure_java_runtime,
    _ensure_project_sdk_dir,
    _find_flutter_cmd,
    _persist_env,
    _print_manual_shell_setup,
    _resolve_android_sdk,
    _write_local_properties,
)
from .scaffold import (
    _apply_cfg_to_project,
    _apply_sim_video_build_setting,
    _apply_simulator_build_settings,
    _copy_kt_into_project,
    _copy_tree,
    _filter_project_devices,
    _infer_entry_class_from_kt,
    _replace_project_placeholders,
)
from .sdk_fetch import _template_under_sdk, resolve_sdk
from .video import _resolve_sim_video


def _resolve_required_dir(
    raw_path: str | Path,
    *,
    label: str,
    subcommand: str,
) -> Path:
    path = Path(raw_path).expanduser().resolve()
    if path.is_dir():
        return path
    raise CliUsageError(f"{label} not found: {path}")


def _resolve_quick_run_template(sdk: Path) -> Path:
    sdk_template = _template_under_sdk(sdk)
    if sdk_template.is_dir():
        return sdk_template
    raise CliUsageError(f"Template not found: {sdk_template}")


def _resolve_init_paths(raw_sdk: str | Path | None, raw_template: str | Path | None) -> tuple[Path, Path]:
    sdk = resolve_sdk(raw_sdk, subcommand="init")

    if raw_template is None:
        template = _template_under_sdk(sdk)
        if template.is_dir():
            return sdk, template
        raise CliUsageError(f"Template not found: {template}")

    template = _resolve_required_dir(raw_template, label="Template", subcommand="init")
    return sdk, template


def _relative_sdk_path_or_absolute(sdk: Path, project_dir: Path) -> str:
    try:
        return Path(os.path.relpath(sdk, project_dir)).as_posix()
    except ValueError:
        # Windows cannot make a relative path across drives; Gradle/YAML accept an absolute SDK path.
        return sdk.as_posix()


def cmd_init(args: argparse.Namespace) -> int:
    dst = Path(args.dir).expanduser().resolve()
    sdk, template = _resolve_init_paths(getattr(args, "sdk", None), getattr(args, "template", None))
    entry_class = _validate_entry_class(args.entry_class, "--entry-class")
    selection = parse_device_selection(getattr(args, "devices", None), sim=bool(getattr(args, "sim", False)))

    if dst.exists() and any(dst.iterdir()):
        raise RuntimeError(f"Target dir must be empty: {dst}")
    dst.mkdir(parents=True, exist_ok=True)

    # Copy a curated subset of the template (avoid build/ caches).
    _copy_tree(template / "app", dst / "app")
    _copy_tree(template / "xgglass_app_logic", dst / "xgglass_app_logic")
    _copy_tree(template / "gradle", dst / "gradle")

    for f in [
        ".gitignore",
        "build.gradle.kts",
        "settings.gradle.kts",
        "gradle.properties",
        "gradlew",
        "gradlew.bat",
        "README.md",
        DEFAULT_CONFIG_FILE,
    ]:
        src = template / f
        if src.exists():
            shutil.copy2(src, dst / f)

    _ensure_executable(dst / "gradlew")

    # Filter device-specific template sections before normal placeholder replacement.
    _filter_project_devices(dst, selection)

    # Patch template placeholders.
    rel_sdk = _relative_sdk_path_or_absolute(sdk, dst)
    _replace_project_placeholders(dst, rel_sdk=rel_sdk, entry_class=entry_class)

    # Patch xg-glass.yaml (if template provides it).
    cfg_file = dst / DEFAULT_CONFIG_FILE
    if not cfg_file.exists():
        cfg_file.write_text(
            "\n".join(
                [
                    "# xg-glass config (generated by xg-glass init)",
                    f'sdkPath: "{rel_sdk}"',
                    f'entryClass: "{entry_class}"',
                    f'rayneoMercuryAarDir: "{rel_sdk}/third_party/rayneo/aar"',
                    'variant: "debug"',
                    'module: "app"',
                    'applicationId: "com.example.xgglassapp"',
                    "",
                ]
            ),
            encoding="utf-8",
        )
    elif selection.explicit:
        _record_device_selection(cfg_file, selection)

    # One-click bootstrap: ensure Java/Android SDK/Flutter are usable on a fresh machine,
    # then persist env vars for future shells (macOS: ~/.zshrc).
    env = {**os.environ}
    _ensure_java_runtime(env)
    android_sdk = _resolve_android_sdk()
    if android_sdk:
        env.setdefault("ANDROID_HOME", android_sdk)
        env.setdefault("ANDROID_SDK_ROOT", android_sdk)
    # Generate local.properties with sdk.dir + Rokid config.
    _write_local_properties(dst, android_sdk)
    # Ensure Flutter (downloads managed Flutter + runs pub get if needed).
    cfg = _load_config(dst, DEFAULT_CONFIG_FILE)
    _ensure_flutter_module_ready(dst, cfg, needs_frame=(selection.is_all or "frame" in selection.devices))
    # Persist for future shells
    flutter = _find_flutter_cmd()
    if bool(getattr(args, "no_shell_setup", False)):
        _print_manual_shell_setup(java_home=env.get("JAVA_HOME"), android_sdk=android_sdk, flutter_bin=flutter)
    else:
        _persist_env(java_home=env.get("JAVA_HOME"), android_sdk=android_sdk, flutter_bin=flutter)

    if bool(getattr(args, "sim", False)):
        _apply_simulator_build_settings(dst, enabled=True)

    print(f"Created project: {dst}")
    print("Next:")
    print(f"  cd {dst}")
    print("  xg-glass build")
    print("  # If you prefer Gradle directly in a new terminal:")
    if platform.system() == "Darwin":
        print("  #   source ~/.zshrc")
    else:
        print("  #   restart your terminal")
    print("  #   ./gradlew :app:assembleDebug")
    print("  xg-glass install")
    print("  xg-glass run")
    return 0


def cmd_build(args: argparse.Namespace) -> int:
    project = Path(args.project).expanduser().resolve()
    sdk_override = None
    if args.sdk:
        sdk_override = str(_resolve_required_dir(args.sdk, label="SDK", subcommand="build"))
    cfg = _load_config(project, args.config)
    cfg = _apply_overrides(
        cfg,
        sdk=sdk_override,
        entry_class=args.entry_class,
        rayneo_aar_dir=args.rayneo_aar_dir,
        variant=args.variant,
        module=args.module,
    )
    _apply_cfg_to_project(project, cfg)

    # Ensure all development dependencies are available.
    # This allows standalone `xg-glass build` (without prior `init`) on a fresh machine.
    env = {**os.environ}
    _ensure_java_runtime(env)
    android_sdk = _resolve_android_sdk()
    if android_sdk:
        env.setdefault("ANDROID_HOME", android_sdk)
        env.setdefault("ANDROID_SDK_ROOT", android_sdk)
        # Ensure project local.properties has sdk.dir (may be missing if user
        # cloned the project instead of using `xg-glass init`).
        _ensure_project_sdk_dir(project, android_sdk)
    _ensure_flutter_module_ready(project, cfg)

    # Persist env vars so future shells (e.g. manual ./gradlew) also work.
    # Idempotent – no-op if already written.
    flutter = _find_flutter_cmd()
    _persist_env(java_home=env.get("JAVA_HOME"), android_sdk=android_sdk, flutter_bin=flutter)

    # Gradle's Flutter plugin invokes engine binaries (impellerc, gen_snapshot).
    # On macOS these may carry quarantine; strip before Gradle runs.
    _ensure_flutter_executables()

    variant = cfg.variant
    module = cfg.module
    gradlew = _gradlew_path(project)
    task = f":{module}:assemble{_cap(variant)}"
    _run([str(gradlew), task], cwd=project, env=env)
    apk_dir = project / module / "build" / "outputs" / "apk" / variant
    print(f"Build OK. APK outputs under: {apk_dir}")
    return 0


def cmd_install(args: argparse.Namespace) -> int:
    project = Path(args.project).expanduser().resolve()
    cfg = _load_config(project, args.config)
    cfg = _apply_overrides(cfg, variant=args.variant, module=args.module)
    module = cfg.module
    variant = cfg.variant

    apk = Path(args.apk).expanduser().resolve() if args.apk else _pick_apk(project, module, variant, args.serial)
    if not apk.exists():
        raise FileNotFoundError(f"APK not found: {apk}")

    cmd = [_find_adb_cmd()]
    if args.serial:
        cmd += ["-s", args.serial]
    cmd += ["install", "-r", str(apk)]
    _run(cmd, cwd=project)
    print(f"Installed: {apk.name}")
    return 0


def cmd_run(args: argparse.Namespace) -> int:
    sim_enabled = bool(getattr(args, "sim", False))

    # Stage 3: quick mode - run a single .kt file by generating a project.
    if getattr(args, "kt_file", None) and str(args.kt_file).lower().endswith(".kt"):
        kt = Path(args.kt_file).expanduser().resolve()
        if not kt.exists():
            raise FileNotFoundError(f"Kotlin file not found: {kt}")

        sdk = resolve_sdk(getattr(args, "sdk", None), subcommand="run")
        template = _resolve_quick_run_template(sdk)

        raw_entry_class = getattr(args, "entry_class", None)
        entry_class = raw_entry_class or _infer_entry_class_from_kt(kt)
        if not entry_class:
            raise RuntimeError(
                "Failed to infer entry class from .kt file. Please ensure the file has a `package ...` line and a top-level `class`, "
                "or pass --entry-class explicitly."
            )
        entry_class = _validate_entry_class(
            entry_class,
            "--entry-class" if raw_entry_class else "inferred entry class",
        )

        if getattr(args, "save", None):
            project_dir = Path(args.save).expanduser().resolve()
            if project_dir.exists() and any(project_dir.iterdir()):
                raise RuntimeError(f"--save directory must be empty: {project_dir}")
            project_dir.parent.mkdir(parents=True, exist_ok=True)
            project_dir.mkdir(parents=True, exist_ok=True)
            keep = True
        else:
            base = Path.cwd() / ".xg_glass_tmp"
            base.mkdir(parents=True, exist_ok=True)
            project_dir = Path(tempfile.mkdtemp(prefix="run-", dir=str(base)))
            keep = bool(getattr(args, "keep_tmp", False))

        _init_project(dst=project_dir, template=template, sdk=sdk, entry_class=entry_class)
        _copy_kt_into_project(project_dir, kt)

        sim_video = _prepare_simulator_run_project(project_dir, args) if sim_enabled else None
        _build_install_run_project(project_dir, args, ensure_simulator=sim_enabled, sim_video=sim_video)

        if not keep:
            shutil.rmtree(project_dir, ignore_errors=True)
        else:
            print(f"Quick project kept at: {project_dir}")
        return 0

    if sim_enabled:
        project_dir = Path(args.project).expanduser().resolve()
        sim_video = _prepare_simulator_run_project(project_dir, args)
        return _build_install_run_project(project_dir, args, ensure_simulator=True, sim_video=sim_video)

    return _run_project(args)


def _prepare_simulator_run_project(project_dir: Path, args: argparse.Namespace) -> Path | None:
    _apply_simulator_build_settings(project_dir, enabled=True)
    sim_video = _resolve_sim_video(args)
    if sim_video is not None:
        _apply_sim_video_build_setting(project_dir, _DEVICE_VIDEO_PATH)
    else:
        _apply_sim_video_build_setting(project_dir, "")
    return sim_video


def _build_install_run_project(
    project_dir: Path,
    args: argparse.Namespace,
    *,
    ensure_simulator: bool,
    sim_video: Path | None,
) -> int:
    variant = getattr(args, "variant", "debug")
    module = getattr(args, "module", "app")
    config = getattr(args, "config", DEFAULT_CONFIG_FILE)
    serial = getattr(args, "serial", None)
    package = getattr(args, "package", None)

    cmd_build(
        argparse.Namespace(
            project=str(project_dir),
            variant=variant,
            module=module,
            config=config,
            entry_class=None,
            sdk=None,
            rayneo_aar_dir=None,
        )
    )

    if ensure_simulator:
        _ensure_emulator_running(serial=serial)

    if sim_video is not None:
        _push_video_to_device(sim_video, serial=serial)

    cmd_install(
        argparse.Namespace(
            project=str(project_dir),
            variant=variant,
            module=module,
            config=config,
            serial=serial,
            apk=None,
        )
    )

    return _run_project(
        argparse.Namespace(
            project=str(project_dir),
            variant=variant,
            module=module,
            config=config,
            serial=serial,
            package=package,
            kt_file=None,
            save=None,
            keep_tmp=False,
            entry_class=None,
            sdk=None,
        )
    )


def _run_project(args: argparse.Namespace) -> int:
    project = Path(args.project).expanduser().resolve()
    cfg = _load_config(project, args.config)
    cfg = _apply_overrides(cfg, module=args.module, variant=args.variant)
    module = cfg.module
    package_name = args.package or cfg.application_id or _read_application_id(project, module) or "com.example.xgglassapp"

    cmd = [_find_adb_cmd()]
    if getattr(args, "serial", None):
        cmd += ["-s", args.serial]
    template_cmd = cmd + ["shell", "am", "start", "-n", f"{package_name}/.MainActivity"]
    try:
        _run_am_start(template_cmd, cwd=project)
    except subprocess.CalledProcessError:
        # Fall back for hand-edited apps that kept the CLI config but renamed the activity.
        cmd += ["shell", "monkey", "-p", package_name, "-c", "android.intent.category.LAUNCHER", "1"]
        _run(cmd, cwd=project)
    print(f"Launched: {package_name}")
    return 0


def _run_am_start(cmd: list[str], cwd: Path) -> None:
    print("+", " ".join(cmd))
    completed = subprocess.run(
        cmd,
        cwd=str(cwd),
        text=True,
        stdout=subprocess.PIPE,
        stderr=subprocess.STDOUT,
        check=False,
    )
    output = completed.stdout or ""
    if output:
        print(output, end="" if output.endswith("\n") else "\n")
    if completed.returncode != 0 or _am_start_output_failed(output):
        raise subprocess.CalledProcessError(completed.returncode or 1, cmd, output=output)


def _am_start_output_failed(output: str) -> bool:
    for line in output.splitlines():
        lowered = line.lower()
        if "error" in lowered or "does not exist" in lowered:
            return True
    return False


def _init_project(*, dst: Path, template: Path, sdk: Path, entry_class: str) -> None:
    """
    Internal helper: same behavior as `xg-glass init`, but callable from quick mode.
    """
    cmd_init(
        argparse.Namespace(
            dir=str(dst),
            template=str(template),
            sdk=str(sdk),
            entry_class=str(entry_class),
        )
    )


def _record_device_selection(cfg_file: Path, selection: DeviceSelection) -> None:
    devices_line = f"devices: {format_devices_yaml_value(selection)}"
    text = cfg_file.read_text(encoding="utf-8")
    lines = text.splitlines()
    for idx, line in enumerate(lines):
        if line.strip().startswith("devices:"):
            # This updater intentionally supports only the generated single-line
            # form: devices: [even, simulator]. Multi-line YAML would need a real
            # YAML parser so do not rewrite it as if it were one line.
            if line.split(":", 1)[1].strip() == "":
                raise CliUsageError(
                    "Cannot update multi-line devices entry in xg-glass.yaml; use a single-line "
                    "form such as devices: [even, simulator]."
                )
            lines[idx] = devices_line
            cfg_file.write_text("\n".join(lines) + "\n", encoding="utf-8")
            return

    suffix = "" if text.endswith("\n") else "\n"
    cfg_file.write_text(text + suffix + devices_line + "\n", encoding="utf-8")
