package com.example.xgglassapp.logic

import com.universalglasses.appcontract.UniversalAppContext
import com.universalglasses.appcontract.UniversalAppEntrySimple
import com.universalglasses.appcontract.UniversalCommand
import com.universalglasses.core.DisplayOptions

/*
 * Example developer entry.
 *
 * In a third-party app, this is where the developer writes the business logic:
 * `client.connect()`, `client.capturePhoto()`, `client.display(...)`, etc.
 *
 * The RayNeo glass-host APK (generated by our Gradle plugin) loads this class by reflection.
 */

class AutoSolverEntry : UniversalAppEntrySimple {
    override val id: String = "auto_solver"
    override val displayName: String = "Auto Solver"

    override fun commands(): List<UniversalCommand> {
        // One entry, run across devices.

        // -- Rokid/Frame: runs on PHONE host (talks to glasses as a peripheral)
        // -- RayNeo: runs on GLASSES host (PHONE host is installer-only and will be hidden by default policy)

        // Note: we keep this example minimal: capture -> display (no cloud AI).

        val captureThenDisplay = object : UniversalCommand {
            override val id: String = "capture_then_display"
            override val title: String = "Capture -> Display"
            override suspend fun run(ctx: UniversalAppContext): Result<Unit> {
                val r = ctx.client.capturePhoto()
                val img = r.getOrNull()
                ctx.log("capturePhoto: ok=${r.isSuccess} bytes=${img?.jpegBytes?.size ?: 0}")
                if (img == null) {
                    return Result.failure(r.exceptionOrNull() ?: RuntimeException("capturePhoto failed"))
                }

                // Let the PHONE host show a preview when available.
                ctx.onCapturedImage?.invoke(img)

                val text = "Captured ${img.jpegBytes.size} bytes"
                val dr = ctx.client.display(text, DisplayOptions())
                ctx.log("display: ok=${dr.isSuccess}")

                return dr
            }
        }

        return listOf(captureThenDisplay)
    }
}